title: "AROSA Foundation"
author: "Dr. Aaron Siegel"
description: "Dedicated to advancing AI research through openness, collaboration, and ethical practices. This is AROSA foundation."


theme: "minima"

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
